# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today I Learned
email: til@spenser.io
description: > # this means to ignore newlines until "baseurl:"
  A TIL site created by Spenser Pothier with my learnings of the day that I don't want to forget.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: spenserpothier
github_username:  spenserpothier

# Build settings
markdown: kramdown
